### ISSUE TITLE
Where can the resulting AppImages be downloaded?

### ISSUE THREAD

**Issue by probonopd** [Calinou/godot-builds-ci#1]
Where can the resulting AppImages be downloaded? Maybe this could be documented in README.md. Thanks.

**Comment by Calinou** [comment]
They're on [this page](https://godot.hugo.pro/builds/) now (check `editor/` inside each version directory); note that some directories do not contain all platforms (since some builds may have failed).

I'll set up a proper website later, once I get AppVeyor deployment working (which builds for Windows – I've gotten the build working, but not deployment).

**Comment by probonopd** [comment]
Thank you @Calinou - is there any way you could provide a permalink that would always redirect to the latest AppImage? This would be very useful for getting it into the AppImageHub central directory of available AppImages.

**Comment by Calinou** [comment]
A permalink is now available at <https://archive.hugo.pro/builds/godot/editor/godot-linux-nightly-x86_64.AppImage>. Note that this is an unofficial nightly build, so it should be clearly noted on AppImageHub.
