### ISSUE TITLE
Windows + Linux + Android + HTML5 export template does not include Android templates

### ISSUE THREAD

**Issue by zlsa** [Calinou/godot-builds-ci#18]
Previously #14

**Comment by Calinou** [comment]
For the record, Android builds are currently broken on x86 due to https://github.com/godotengine/godot/issues/31407. https://github.com/Calinou/godot-builds-ci/commit/cd98edb8cfd8a0af22ba9d555a787e98bb717867 disables x86 Android builds in the meantime.

If all goes well, they should be available again in a few hours from now :slightly_smiling_face:
