### ISSUE TITLE
Android template is corrupted

### ISSUE THREAD

**Issue by sami8github** [Calinou/godot-builds-ci#4]
It say : cant open export template.
and when change extension from tpz to zip it say the file is corrupted (other tpz files can be opened with zip extension correctly but android.tpz no)

**Comment by Calinou** [comment]
I can confirm this issue; it seems to affect all export templates that bundle ZIP archives in some way (APK files are ZIP archives with a renamed extension).

I don't know how to fix it though. Some archiving software (such as Ark on Linux) will let you extract corrupted ZIP archives and you will be able to install export templates manually in this case (by placing them into `%APPDATA%\Godot\templates\3.1.dev\` on Windows, `~/Library/Application Support/Godot/templates/3.1.dev` on macOS or `$HOME/.local/share/godot/templates/3.1.dev/` on Linux).

Anyway, I plan to tweak the export template generation so that only two TPZ files are generated: one for all platforms except macOS and iOS (since these are built on Travis CI instead of GitLab CI), and one for macOS and iOS. This way, it will be easier and faster for users to install export templates (less clicks needed).

**Comment by sami8github** [comment]
I tried the folowing :
repare android.tpz.zip , extract files and copy them to template folder ,debug file is corrupted the release is ok , export to android with release and gles 2.0 and 3.0 it exported but none of them work ,testing device condor p6 pro.
tried export to windows it worked.

**Comment by sami8github** [comment]
how about creating the needed apk without compress them in tpz ?

**Comment by Calinou** [comment]
> how about creating the needed apk without compress them in tpz ?

If I do that, then it wouldn't be possible to make the Godot editor install them for you anymore; you would have to drag the APKs manually into the aforementioned folders. I want to keep the installation experience as easy as possible, so I'm afraid it's not an option.

**Comment by sami8github** [comment]
but manual install is better than nothing (the tpz is broken and files are really needed)
and after repairing the tpz the files inside still corrupted.
if its possible can you please provide them once with the other files ?

**Comment by Calinou** [comment]
I started work on amalgamating several platforms into a single TPZ file. Try [this one](https://archive.hugo.pro/builds/godot/templates/godot-templates-android-html5-linux-windows-nightly.tpz); it seems to install successfully in Godot here.

I'm doing the same for macOS and iOS templates right now; once this is done, I will update the website to point to the new export templates.

**Comment by sami8github** [comment]
Perfect ,it works very nicely
Thank you very very much
